hostname = '< OAC HOST NAME>'
UserName = '<USERNAME>'
Password = '<PASSWORD>'
namespace = '<TENANCY NAMESPACE>'
bucket = '<BUCKET_NAME>'
prefix = '<PREFIX_FOR_FILENAME>'
SnapPassword = '<SNAPSHOT_PASSWORD>'
